/* 
 * @(#)Cont.java        1.0 10/7/12
 *
 * This file has been auto-generated by JPyang, the Java output format plug-in
 * of pyang. Origin: module "containerTest", revision: "unknown".
 */

package cont;

import com.tailf.confm.*;
import com.tailf.inm.*;
import java.util.Hashtable;

/**
 * The root class for namespace http://testCom/ns/cont/10 (accessible from 
 * Cont.NAMESPACE) with prefix "cont" (Cont.PREFIX).
 *
 * @version    1.0 2012-7-10
 * @author    Auto Generated
 */
public class Cont {

    public static final String NAMESPACE = "http://testCom/ns/cont/10";

    public static final String PREFIX = "cont";
    
    /**
     * Enable the elements in this namespace to be aware
     * of the data model and use the generated classes.
     */
    public static void enable() throws INMException {
        Container.setPackage(NAMESPACE, PREFIX);
        Cont.registerSchema();
    }

    /**
     * Register the schema for this namespace in the global
     * schema table (CsTree) making it possible to lookup
     * CsNode entries for all tagpaths
     */
    public static void registerSchema() throws INMException {
        StackTraceElement[] sTrace = (new Exception()).getStackTrace();
        ClassLoader loader = sTrace[0].getClass().getClassLoader();
        java.net.URL schemaUrl = loader.getSystemResource("Cont.schema");
        SchemaParser parser = new SchemaParser();
        Hashtable h = CsTree.create(NAMESPACE);
        if (schemaUrl == null)
            parser.readFile("src/cont/Cont.schema", h);
        else
            parser.readFile(schemaUrl, h);
    }

}