/* 
 * @(#)Naming-test.java        1.0 13/7/12
 *
 * This file has been auto-generated by JPyang, the Java output format plug-in
 * of pyang. Origin: module "namingTest", revision: "unknown".
 */

package naming;

import com.tailf.confm.*;
import com.tailf.inm.*;
import java.util.Hashtable;

/**
 * The root class for namespace http://test.com/ns/naming-test/1.0 (accessible from 
 * Naming-test.NAMESPACE) with prefix "naming-test" (Naming-test.PREFIX).
 *
 * @version    1.0 2012-7-13
 * @author    Auto Generated
 */
public class NamingTest {

    public static final String NAMESPACE = "http://test.com/ns/naming-test/1.0";

    public static final String PREFIX = "naming-test";
    
    /**
     * Enable the elements in this namespace to be aware
     * of the data model and use the generated classes.
     */
    public static void enable() throws INMException {
        Container.setPackage(NAMESPACE, PREFIX);
        NamingTest.registerSchema();
    }

    /**
     * Register the schema for this namespace in the global
     * schema table (CsTree) making it possible to lookup
     * CsNode entries for all tagpaths
     */
    public static void registerSchema() throws INMException {
        StackTraceElement[] sTrace = (new Exception()).getStackTrace();
        ClassLoader loader = sTrace[0].getClass().getClassLoader();
        java.net.URL schemaUrl = loader.getSystemResource("Naming-test.schema");
        SchemaParser parser = new SchemaParser();
        Hashtable h = CsTree.create(NAMESPACE);
        if (schemaUrl == null)
            parser.readFile("Naming-test.schema", h);
        else
            parser.readFile(schemaUrl, h);
    }

}